// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: variants.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckProductVariantRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductVariantId uint32                 `protobuf:"varint,1,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckProductVariantRequest) Reset() {
	*x = CheckProductVariantRequest{}
	mi := &file_variants_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductVariantRequest) ProtoMessage() {}

func (x *CheckProductVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variants_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductVariantRequest.ProtoReflect.Descriptor instead.
func (*CheckProductVariantRequest) Descriptor() ([]byte, []int) {
	return file_variants_proto_rawDescGZIP(), []int{0}
}

func (x *CheckProductVariantRequest) GetProductVariantId() uint32 {
	if x != nil {
		return x.ProductVariantId
	}
	return 0
}

type CheckProductVariantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductVariantResponse) Reset() {
	*x = CheckProductVariantResponse{}
	mi := &file_variants_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductVariantResponse) ProtoMessage() {}

func (x *CheckProductVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variants_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductVariantResponse.ProtoReflect.Descriptor instead.
func (*CheckProductVariantResponse) Descriptor() ([]byte, []int) {
	return file_variants_proto_rawDescGZIP(), []int{1}
}

func (x *CheckProductVariantResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckProductVariantResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetProductVariantsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductVariantIds []uint32               `protobuf:"varint,1,rep,packed,name=product_variant_ids,json=productVariantIds,proto3" json:"product_variant_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProductVariantsRequest) Reset() {
	*x = GetProductVariantsRequest{}
	mi := &file_variants_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductVariantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductVariantsRequest) ProtoMessage() {}

func (x *GetProductVariantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variants_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductVariantsRequest.ProtoReflect.Descriptor instead.
func (*GetProductVariantsRequest) Descriptor() ([]byte, []int) {
	return file_variants_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductVariantsRequest) GetProductVariantIds() []uint32 {
	if x != nil {
		return x.ProductVariantIds
	}
	return nil
}

type GetProductVariantsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductVariants []*ProductVariant      `protobuf:"bytes,1,rep,name=product_variants,json=productVariants,proto3" json:"product_variants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProductVariantsResponse) Reset() {
	*x = GetProductVariantsResponse{}
	mi := &file_variants_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductVariantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductVariantsResponse) ProtoMessage() {}

func (x *GetProductVariantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variants_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductVariantsResponse.ProtoReflect.Descriptor instead.
func (*GetProductVariantsResponse) Descriptor() ([]byte, []int) {
	return file_variants_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductVariantsResponse) GetProductVariants() []*ProductVariant {
	if x != nil {
		return x.ProductVariants
	}
	return nil
}

var File_variants_proto protoreflect.FileDescriptor

var file_variants_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x52, 0x0a, 0x1b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x4b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x73, 0x22, 0x5e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x40, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x73, 0x32, 0xd6, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x19,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x59, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_variants_proto_rawDescOnce sync.Once
	file_variants_proto_rawDescData []byte
)

func file_variants_proto_rawDescGZIP() []byte {
	file_variants_proto_rawDescOnce.Do(func() {
		file_variants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_variants_proto_rawDesc), len(file_variants_proto_rawDesc)))
	})
	return file_variants_proto_rawDescData
}

var file_variants_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_variants_proto_goTypes = []any{
	(*CheckProductVariantRequest)(nil),  // 0: proto.CheckProductVariantRequest
	(*CheckProductVariantResponse)(nil), // 1: proto.CheckProductVariantResponse
	(*GetProductVariantsRequest)(nil),   // 2: proto.GetProductVariantsRequest
	(*GetProductVariantsResponse)(nil),  // 3: proto.GetProductVariantsResponse
	(*ProductVariant)(nil),              // 4: proto.ProductVariant
}
var file_variants_proto_depIdxs = []int32{
	4, // 0: proto.GetProductVariantsResponse.product_variants:type_name -> proto.ProductVariant
	0, // 1: proto.ProductVariantService.CheckProductVariantExists:input_type -> proto.CheckProductVariantRequest
	2, // 2: proto.ProductVariantService.GetProductVariants:input_type -> proto.GetProductVariantsRequest
	1, // 3: proto.ProductVariantService.CheckProductVariantExists:output_type -> proto.CheckProductVariantResponse
	3, // 4: proto.ProductVariantService.GetProductVariants:output_type -> proto.GetProductVariantsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_variants_proto_init() }
func file_variants_proto_init() {
	if File_variants_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_variants_proto_rawDesc), len(file_variants_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_variants_proto_goTypes,
		DependencyIndexes: file_variants_proto_depIdxs,
		MessageInfos:      file_variants_proto_msgTypes,
	}.Build()
	File_variants_proto = out.File
	file_variants_proto_goTypes = nil
	file_variants_proto_depIdxs = nil
}
