// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: variants.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductVariantService_CheckProductVariantExists_FullMethodName = "/proto.ProductVariantService/CheckProductVariantExists"
	ProductVariantService_GetProductVariants_FullMethodName        = "/proto.ProductVariantService/GetProductVariants"
)

// ProductVariantServiceClient is the client API for ProductVariantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductVariantServiceClient interface {
	CheckProductVariantExists(ctx context.Context, in *CheckProductVariantRequest, opts ...grpc.CallOption) (*CheckProductVariantResponse, error)
	GetProductVariants(ctx context.Context, in *GetProductVariantsRequest, opts ...grpc.CallOption) (*GetProductVariantsResponse, error)
}

type productVariantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductVariantServiceClient(cc grpc.ClientConnInterface) ProductVariantServiceClient {
	return &productVariantServiceClient{cc}
}

func (c *productVariantServiceClient) CheckProductVariantExists(ctx context.Context, in *CheckProductVariantRequest, opts ...grpc.CallOption) (*CheckProductVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckProductVariantResponse)
	err := c.cc.Invoke(ctx, ProductVariantService_CheckProductVariantExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productVariantServiceClient) GetProductVariants(ctx context.Context, in *GetProductVariantsRequest, opts ...grpc.CallOption) (*GetProductVariantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductVariantsResponse)
	err := c.cc.Invoke(ctx, ProductVariantService_GetProductVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductVariantServiceServer is the server API for ProductVariantService service.
// All implementations must embed UnimplementedProductVariantServiceServer
// for forward compatibility.
type ProductVariantServiceServer interface {
	CheckProductVariantExists(context.Context, *CheckProductVariantRequest) (*CheckProductVariantResponse, error)
	GetProductVariants(context.Context, *GetProductVariantsRequest) (*GetProductVariantsResponse, error)
	mustEmbedUnimplementedProductVariantServiceServer()
}

// UnimplementedProductVariantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductVariantServiceServer struct{}

func (UnimplementedProductVariantServiceServer) CheckProductVariantExists(context.Context, *CheckProductVariantRequest) (*CheckProductVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckProductVariantExists not implemented")
}
func (UnimplementedProductVariantServiceServer) GetProductVariants(context.Context, *GetProductVariantsRequest) (*GetProductVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductVariants not implemented")
}
func (UnimplementedProductVariantServiceServer) mustEmbedUnimplementedProductVariantServiceServer() {}
func (UnimplementedProductVariantServiceServer) testEmbeddedByValue()                               {}

// UnsafeProductVariantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductVariantServiceServer will
// result in compilation errors.
type UnsafeProductVariantServiceServer interface {
	mustEmbedUnimplementedProductVariantServiceServer()
}

func RegisterProductVariantServiceServer(s grpc.ServiceRegistrar, srv ProductVariantServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductVariantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductVariantService_ServiceDesc, srv)
}

func _ProductVariantService_CheckProductVariantExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckProductVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductVariantServiceServer).CheckProductVariantExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductVariantService_CheckProductVariantExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductVariantServiceServer).CheckProductVariantExists(ctx, req.(*CheckProductVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductVariantService_GetProductVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductVariantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductVariantServiceServer).GetProductVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductVariantService_GetProductVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductVariantServiceServer).GetProductVariants(ctx, req.(*GetProductVariantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductVariantService_ServiceDesc is the grpc.ServiceDesc for ProductVariantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductVariantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductVariantService",
	HandlerType: (*ProductVariantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckProductVariantExists",
			Handler:    _ProductVariantService_CheckProductVariantExists_Handler,
		},
		{
			MethodName: "GetProductVariants",
			Handler:    _ProductVariantService_GetProductVariants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "variants.proto",
}
